### PR TITLE
Debug info for DOR metagraph alpha 14 invalid signatures error -- do not merge test only

### PR DESCRIPTION
**Pull request by ryle-goehausen**
This is off alpha 14 branch. Adding an immediate verification after the signature, and debug info for the warning log statement to manually validate the signature data that is being produced to figure out why it's invalid.

### CODE REVIEW

**Comment by marcinwadon** [comment]
If this is off an `alpha 14` branch, why you would like to merge it back to `develop`? Can't you keep it just on the branch for testing?

**Comment by ryle-goehausen** [comment]
I can change the target branch, I needed a PR to run the E2E CI

**Comment by marcinwadon** [comment]
Ok, got it. Then the base branch doesn't matter. I don't know what branch you'd like to change it too btw :)

**Comment by TheMMaciek** [comment]
Can we close this PR @ryle-goehausen ?

**Pull request closed without merging**
