### PR TITLE
ci: action for linting commit names and optional local hook

### PR DESCRIPTION
**Pull request by marcinwadon**
To configure local hook for commit name linting:
1. Install `npm`,
2. Run `npm install` to install packages,
3. Run `npx husky`.

### CODE REVIEW

**Review by IPadawans — DISMISSED** [review]
LGTM

**Comment by IPadawans** [comment]
Quick typo I think, it should be `yarn husky` no? @marcinwadon

**Review by scasplte2 — DISMISSED** [review]

**Comment by marcinwadon** [comment]
Thank you @IPadawans. I've updated it to use `npm`, as people most likely would have `npm` already preinstalled.

**Review by IPadawans — APPROVED** [review]
👍🏼

**Review by kpudlik — APPROVED** [review]

**Pull request merged**
