### PR TITLE
Splitting the Github action on 2: DAG and Currency

### PR DESCRIPTION
**Pull request by IPadawans**

### CODE REVIEW

**Comment by marcinwadon** [comment]
@IPadawans by splitting actions I meant one action to be compilation and scala tests (exactly as it was before) and the second action your tests on a running cluster. That way we can simply require the code to be compilable (with passing unit tests) separately from the long running tests on the cluster.

**Comment by marcinwadon** [comment]
btw - missing label

**Comment by marcinwadon** [comment]
hey @IPadawans, will you work on that or it's already deprecated?

**Comment by IPadawans** [comment]
> hey @IPadawans, will you work on that or it's already deprecated?

I'll work on this, I didn't work yet because we have the high priority things with metagraphs

**Pull request closed without merging**
