### PR TITLE
Add EpochProgress to CurrencySnapshot

### PR DESCRIPTION
**Pull request by kpudlik**

### CODE REVIEW

**Review by IPadawans — APPROVED** [review]
As far as I understand the code of the tessellation project, it seems great to me

**Review by TheMMaciek — DISMISSED** [review]

**Review by marcinwadon — DISMISSED** [review]

**Comment by marcinwadon** [comment]
@kpudlik does it mean this PR requires full reset of testnet and integrationnet, as the schema changed?

**Comment by kpudlik** [comment]
> @kpudlik does it mean this PR requires full reset of testnet and integrationnet, as the schema changed?

Yes

**Review by sdavidp — COMMENTED** [review]
👍

**Review by marcinwadon — APPROVED** [review]

**Pull request merged**
