### PR TITLE
Break Currency L0 validator joining to Currency L0 initial validator

### PR DESCRIPTION
**Pull request by sdavidp**
**This PR is not meant to be merged**

It's sole purpose is to see if the automated github actions will fail by reverting a fix done a few PRs ago:
We expect the github actions to fail.

When I ran it locally:

1. Launch Global initial (genesis) node
2. Launch Currency L0 initial validator (c0)
3. Launch Currency L0 validator (c1)
4. Join c1 to c0
5. 404 error reported in the node logs

The error does not happen in the current develop branch

cc: @ryle-goehausen @AlexBrandes

### CODE REVIEW

**Comment by marcinwadon** [comment]
@sdavidp make sure that the action runs multiple L0 nodes. If the error does not occur, probably it runs a single node

**Comment by TheMMaciek** [comment]
Is this PR still needed? 🤔

**Comment by sdavidp** [comment]
> 

I kept it alive so we could re-check at a later date.

**Comment by marcinwadon** [comment]
@sdavidp you can take a look at https://github.com/nektos/act and I believe we can close the pull request. whenever there would be a need for re-test you can create a new PR based on that branch. also, the branch is already outdated and noone is keeping it up to date

**Pull request closed without merging**
